### ISSUE TITLE
Wishlist success popup overlapping issue

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Internal---Alec-Store-Redesign---6-June-2022#18]
Bug - Chat us button overlapping when wishlist added popup appears.
Exp - wishlist added popup should not get hide behind chat us button.
Ref link - https://drive.google.com/file/d/1u6EBzfRKxoeLYCA9IUT8byZOKoQtbiOU/view

**Comment by ankitcedcoss** [comment]
Bug Not Fixed
https://nimb.ws/elUNFL

**Comment by ui-kuldeep** [comment]
there is no isssue in my browser

**Comment by ankitcedcoss** [comment]
Bug Fixed
