### ISSUE TITLE
Price filter selection not showing on filter

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Internal---Alec-Store-Redesign---6-June-2022#8]
Bug - If user selects availability filter then shows count but on selection price filter then count not showing on filter or not increasing count.
Exp - If user selects price filter then show count on filter. and if user selects both filter type availability and price then count should be visible on 2.
- Show clear all button on filter on collection page.
Ref link - https://drive.google.com/file/d/16q7lhGxFyl2NoZbsfoXs30PfUNVGnMvH/view

**Comment by devSharibAli** [comment]
in theme functionality it does not count it as a tag so it won't count

**Comment by ankitcedcoss** [comment]
Closing on Not Required
